### ISSUE TITLE
[Bug] 회원 가입 후 캐릭터 생성 시 403 에러 발생

### ISSUE THREAD

**Issue by duddn2012** [Charge-Evolution-Battle-on-Earth/Client#46]
### 상황
회원 가입 직후 이동되는 캐릭터 생성 화면에서 나라 리스트를 불러오지 못하는 것 같음

![image](https://github.com/Charge-Evolution-Battle-on-Earth/Client/assets/31121731/e81ec6e0-c205-403d-bd71-e0a9a2e59c2f)

**Comment by rabbitmjh** [comment]
https://github.com/Charge-Evolution-Battle-on-Earth/Client/pull/41
해결 완료
