### ISSUE TITLE
[Bug] 게임 시작 관련 오류

### ISSUE THREAD

**Issue by duddn2012** [Charge-Evolution-Battle-on-Earth/Client#47]
### 상황
Local에서 두 다른 사용자가 로그인 후, 하나의 방에서 매치를 시작하려고 할 때 동작하지 않는 문제

인게임 상황에서 양 플레이어 모두 준비 완료가 된 후, 호스트가 게임 시작을 시도하였지만 어떠한 반응도 없음.

**Comment by rabbitmjh** [comment]
현재는 문제 없이 게임 시작됨
https://github.com/Charge-Evolution-Battle-on-Earth/Client/pull/44
서버에서 오는 메시지의 크기를 늘려 해결
